### ISSUE TITLE
[README] Wrong link in the I18n section

### ISSUE THREAD

**Issue by anthony-robin** [tatey/delayed-web#21]
I just discovered that the link used to show the full set of I18n translations available in the README is redirecting to my own fork (and wrong branch) instead of yours. 

```ruby
You can find the full list here. 
# => should redirect to https://github.com/thebestday/delayed-web/blob/master/config/locales/en.yml
```

Sorry for this mistake 😕

**Comment by Gaurav2728** [comment]
this issue can by close via b27f273ad776c7943199336aa11a3d88fca75952

**Comment by tatey** [comment]
Thanks for the prompt @Gaurav2728 :smile:
