### ISSUE TITLE
ActionView::Template::Error: link_tree argument must be a directory

### ISSUE THREAD

**Issue by DerekCrosson** [tatey/delayed-web#28]
I have ```delyed_web``` installed in a Rails 6 API only app. I get the following errors when I go to ```http://localhost:3000/jobs```:
```
ActionView::Template::Error: link_tree argument must be a directory
```
and
```
no implicit conversion of nil into Array
```

Any idea why this is happening? Are the directories I need to manually add or should I change my ```app/assets/config/manifest.js``` file? This is what it looks like:
```
//= link_tree ../fonts
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

The error is happening in: ```Delayed::Web::JobsController#index```

**Comment by DerekCrosson** [comment]
Ended up having to put this in:
```//= link delayed/web/application.css```

**Comment by Julian-Jurai** [comment]
You probably deleted  the `../fonts` or `../images` directories accidentally

**Comment by dsomel21** [comment]
For me, I was `link_tree`ing to directories that were empty (or filled with `.keep`).

E.g. You might be doing something like: `//= link_tree ../../../vendor/javascript .js` to a directory that's empty. 

Try deleting that line (not commenting it, deleting it).
